# Generated by Django 3.1 on 2020-10-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20201011_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='undefined', max_length=200),
        ),
    ]
